/**
 * ClawBridge interactive setup wizard.
 *
 * Entry point for `npx clawbridge-agent setup` and `pnpm run setup:wizard`.
 *
 * Three paths:
 *   1. Fresh install  — guided .env generation + docker compose up
 *   2. Migrate from OpenClaw
 *   3. Migrate from NanoClaw / Cyndra
 */
import { spawnSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import crypto from 'crypto';
import path from 'path';

import * as p from '@clack/prompts';
import k from 'kleur';

import {
  auditInstall,
  deactivateSource,
  detectInstall,
  resolveManualPath,
  rollback,
  runMigration,
  type MigrationAudit,
  type MigrationSelection,
  type MigrationSource,
} from './migrate.js';

// ─── Brand helpers ────────────────────────────────────────────────────────────

const USE_ANSI = Boolean(process.stdout.isTTY) && !process.env.NO_COLOR;
const TRUECOLOR = USE_ANSI && (process.env.COLORTERM === 'truecolor' || process.env.COLORTERM === '24bit');

function brand(s: string): string {
  if (!USE_ANSI) return s;
  if (TRUECOLOR) return `\x1b[38;2;43;183;206m${s}\x1b[0m`;
  return k.cyan(s);
}
function brandBold(s: string): string {
  if (!USE_ANSI) return s;
  if (TRUECOLOR) return `\x1b[1;38;2;43;183;206m${s}\x1b[0m`;
  return k.bold(k.cyan(s));
}
function dim(s: string): string {
  return USE_ANSI ? k.dim(s) : s;
}

function ensure<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel('Setup cancelled.');
    process.exit(0);
  }
  return value as T;
}

// ─── Intro banner ─────────────────────────────────────────────────────────────

function printBanner(): void {
  const lines = [
    '',
    `  ${brand('/')}  ${brand('/')}  ${brand('/')}  ${brandBold('●')}`,
    ` ${brand('/')}  ${brand('/')}  ${brand('/')}  ${brandBold('●')}   ${k.bold('ClawBridge Agent')}`,
    `${brand('/')}  ${brand('/')}  ${brand('/')}  ${brandBold('●')}    ${dim('AI Agent Platform')}`,
    '',
  ];
  for (const line of lines) console.log(line);
}

// ─── Validation helpers ───────────────────────────────────────────────────────

function validateOAuthToken(value: string | undefined): string | undefined {
  const t = (value ?? '').trim();
  if (!t) return 'Required';
  if (!t.startsWith('sk-ant-oat')) return 'Should start with sk-ant-oat…';
  return undefined;
}

function validateTelegramToken(value: string | undefined): string | undefined {
  const t = (value ?? '').trim();
  if (!t) return 'Required';
  if (!/^\d+:[A-Za-z0-9_-]{35,}$/.test(t)) return 'Expected format: 123456789:ABCdef…';
  return undefined;
}

function validateEmail(value: string | undefined): string | undefined {
  const v = (value ?? '').trim();
  if (!v) return 'Required';
  if (!v.includes('@')) return 'Enter a valid email address';
  return undefined;
}

function validatePassword(value: string | undefined): string | undefined {
  const v = value ?? '';
  if (!v || v.length < 8) return 'Minimum 8 characters';
  return undefined;
}

function validateRequired(value: string | undefined): string | undefined {
  return !(value ?? '').trim() ? 'Required' : undefined;
}

function validateStripeKey(value: string | undefined): string | undefined {
  const v = (value ?? '').trim();
  if (!v) return 'Required';
  if (!v.startsWith('sk_')) return 'Should start with sk_';
  return undefined;
}

function testOAuthToken(token: string): boolean {
  try {
    const result = spawnSync(
      'node',
      [
        '--input-type=module',
        '-e',
        `
import https from 'https';
const opts = {
  hostname: 'api.anthropic.com',
  path: '/v1/models',
  method: 'GET',
  headers: {
    'Authorization': 'Bearer ${token.trim()}',
    'anthropic-version': '2023-06-01',
  },
};
const req = https.request(opts, (res) => {
  process.exit(res.statusCode === 200 || res.statusCode === 404 ? 0 : 1);
});
req.on('error', () => process.exit(0));
req.end();
        `,
      ],
      { encoding: 'utf-8', timeout: 8000 },
    );
    return result.status === 0;
  } catch {
    return true;
  }
}

// ─── .env generation ─────────────────────────────────────────────────────────

interface FreshConfig {
  agentName: string;
  oauthToken: string;
  telegramToken?: string;
  channels: string[];
  adminEmail: string;
  adminPassword: string;
  stripeKey?: string;
  retellKey?: string;
  hindsightDbPassword?: string;
  hindsightApiKey?: string;
  hindsightUrl?: string;
}

function buildEnvFile(cfg: FreshConfig): string {
  const lines: string[] = [
    '# ClawBridge Agent — generated by setup wizard',
    `# Generated: ${new Date().toISOString()}`,
    '',
    '# Agent identity',
    `ASSISTANT_NAME=${cfg.agentName}`,
    '',
    '# Claude Auth (Claude Pro/Max subscription)',
    '# Get this token by running: claude setup-token',
    `CLAUDE_CODE_OAUTH_TOKEN=${cfg.oauthToken}`,
    '',
    '# Admin portal',
    `ADMIN_EMAIL=${cfg.adminEmail}`,
    `ADMIN_PASSWORD=${cfg.adminPassword}`,
    '',
  ];

  if (cfg.telegramToken) {
    lines.push('# Telegram', `TELEGRAM_BOT_TOKEN=${cfg.telegramToken}`, '');
  }
  if (cfg.channels.includes('discord')) {
    lines.push('# Discord', 'DISCORD_BOT_TOKEN=', '');
  }
  if (cfg.channels.includes('slack')) {
    lines.push('# Slack', 'SLACK_BOT_TOKEN=', 'SLACK_SIGNING_SECRET=', '');
  }
  if (cfg.channels.includes('whatsapp')) {
    lines.push('# WhatsApp', 'WHATSAPP_PHONE_NUMBER_ID=', 'WHATSAPP_ACCESS_TOKEN=', '');
  }
  if (cfg.channels.includes('gmail')) {
    lines.push('# Gmail', 'GMAIL_CLIENT_ID=', 'GMAIL_CLIENT_SECRET=', '');
  }
  if (cfg.stripeKey) {
    lines.push('# Stripe billing', `STRIPE_SECRET_KEY=${cfg.stripeKey}`, '');
  }
  if (cfg.retellKey) {
    lines.push('# Retell AI (voice)', `RETELL_API_KEY=${cfg.retellKey}`, '');
  }
  if (cfg.hindsightDbPassword && cfg.hindsightApiKey && cfg.hindsightUrl) {
    lines.push(
      '# Hindsight semantic memory',
      `HINDSIGHT_URL=${cfg.hindsightUrl}`,
      `HINDSIGHT_API_KEY=${cfg.hindsightApiKey}`,
      `HINDSIGHT_DB_PASSWORD=${cfg.hindsightDbPassword}`,
      '',
    );
  }

  return lines.join('\n') + '\n';
}

// ─── Fresh install flow ───────────────────────────────────────────────────────

async function runFreshInstall(): Promise<void> {
  p.log.step('Starting fresh install…');

  // Step 1 — Claude OAuth token
  p.log.message(
    dim(
      '  To authenticate with Claude, run this in a separate terminal:\n' +
        '    claude setup-token\n' +
        '  then paste the token below.',
    ),
  );
  const oauthToken = ensure(
    await p.password({
      message: 'Paste your Claude OAuth token',
      validate: validateOAuthToken,
    }),
  ) as string;

  const s1 = p.spinner();
  s1.start('Validating Claude token…');
  const tokenValid = testOAuthToken(oauthToken.trim());
  s1.stop(
    tokenValid
      ? k.green('Claude token looks good.')
      : k.yellow('Could not verify token (offline?) — continuing anyway.'),
  );

  // Step 2 — Channels
  type ChannelOption = { value: string; label: string; hint?: string };
  const channelOptions: ChannelOption[] = [
    { value: 'telegram', label: 'Telegram', hint: 'recommended' },
    { value: 'whatsapp', label: 'WhatsApp' },
    { value: 'discord', label: 'Discord' },
    { value: 'slack', label: 'Slack' },
    { value: 'gmail', label: 'Gmail' },
  ];
  const channelChoices = ensure(
    await p.multiselect<string>({
      message: 'Which channels would you like to enable?',
      options: channelOptions,
      required: false,
    }),
  ) as string[];

  // Step 3 — Telegram token (if selected)
  let telegramToken: string | undefined;
  if (channelChoices.includes('telegram')) {
    telegramToken = ensure(
      await p.text({
        message: 'Telegram bot token (from @BotFather)',
        placeholder: '123456789:ABCdef…',
        validate: validateTelegramToken,
      }),
    ) as string;
    telegramToken = telegramToken.trim();
  }

  // Step 4 — Agent name
  const agentNameRaw = ensure(
    await p.text({
      message: 'Agent name',
      placeholder: 'ClawBridge',
      defaultValue: 'ClawBridge',
    }),
  ) as string;
  const agentName = agentNameRaw.trim() || 'ClawBridge';

  // Step 5 — Admin credentials
  const adminEmail = ensure(
    await p.text({
      message: 'Admin email (for portal login)',
      placeholder: 'admin@example.com',
      validate: validateEmail,
    }),
  ) as string;
  const adminPassword = ensure(
    await p.password({
      message: 'Admin password',
      validate: validatePassword,
    }),
  ) as string;

  // Step 6 — Stripe (optional)
  const wantsStripe = ensure(
    await p.confirm({
      message: 'Add Stripe billing keys? (optional — skip for now)',
      initialValue: false,
    }),
  ) as boolean;
  let stripeKey: string | undefined;
  if (wantsStripe) {
    stripeKey = (
      ensure(
        await p.password({
          message: 'Stripe secret key',
          validate: validateStripeKey,
        }),
      ) as string
    ).trim();
  }

  // Step 7 — Retell (optional)
  const wantsRetell = ensure(
    await p.confirm({
      message: 'Add Retell AI voice keys? (optional — skip for now)',
      initialValue: false,
    }),
  ) as boolean;
  let retellKey: string | undefined;
  if (wantsRetell) {
    retellKey = (
      ensure(
        await p.password({
          message: 'Retell API key',
          validate: validateRequired,
        }),
      ) as string
    ).trim();
  }

  // Step 8 — Hindsight (optional)
  const wantsHindsight = ensure(
    await p.confirm({
      message: 'Enable Hindsight semantic memory? (recommended for production — skip for now)',
      initialValue: false,
    }),
  ) as boolean;
  let hindsightDbPassword: string | undefined;
  let hindsightApiKey: string | undefined;
  let hindsightUrl: string | undefined;
  if (wantsHindsight) {
    hindsightDbPassword = crypto.randomBytes(16).toString('hex');
    hindsightApiKey = crypto.randomBytes(16).toString('hex');
    hindsightUrl = 'http://localhost:8888';
    p.log.info(dim('Hindsight credentials generated and will be written to .env'));
  }

  // Generate .env
  const cfg: FreshConfig = {
    agentName,
    oauthToken: oauthToken.trim(),
    telegramToken,
    channels: channelChoices,
    adminEmail: adminEmail.trim(),
    adminPassword,
    stripeKey,
    retellKey,
    hindsightDbPassword,
    hindsightApiKey,
    hindsightUrl,
  };

  const envContent = buildEnvFile(cfg);
  const integrationsDir = path.resolve(new URL(import.meta.url).pathname, '../../../integrations');
  const envPath = path.join(integrationsDir, '.env');

  const confirmWrite = ensure(
    await p.confirm({
      message: `.env will be written to ${envPath}. Continue?`,
      initialValue: true,
    }),
  ) as boolean;
  if (!confirmWrite) {
    p.cancel('Aborted. No files written.');
    process.exit(0);
  }

  fs.writeFileSync(envPath, envContent);
  p.log.success(`.env written to ${envPath}`);

  // docker compose up
  const wantsDocker = ensure(
    await p.confirm({
      message: 'Start ClawBridge with docker compose now?',
      initialValue: true,
    }),
  ) as boolean;
  if (wantsDocker) {
    const s2 = p.spinner();
    s2.start('Running docker compose up -d…');
    const result = spawnSync('docker', ['compose', 'up', '-d'], {
      stdio: ['ignore', 'pipe', 'pipe'],
      encoding: 'utf-8',
      cwd: integrationsDir,
    });
    if (result.error) {
      s2.stop(k.red('Docker not found — install Docker Desktop first: https://docs.docker.com/get-docker/'));
    } else if (result.status === 0) {
      s2.stop(k.green('ClawBridge is running.'));
    } else {
      s2.stop(k.yellow('docker compose returned an error — check output below.'));
      if (result.stderr) console.error(result.stderr);
    }
  }

  p.outro(k.green('✅ ClawBridge is running!') + `  Portal: ${k.bold('http://localhost:4000')}`);
}

// ─── Migration audit display ──────────────────────────────────────────────────

function printAuditReport(source: MigrationSource, audit: MigrationAudit): void {
  const typeLabel: Record<string, string> = {
    openclaw: 'OpenClaw',
    nanoclaw: 'NanoClaw',
    cyndra: 'Cyndra',
  };
  const label = typeLabel[source.type] ?? source.type;
  const rows: Array<[string, string]> = [
    ['Groups found:', String(audit.groups.length)],
    ['Messages:', audit.messageCount.toLocaleString()],
    ['Custom skills:', String(audit.skills.length)],
    ['Channels:', audit.channels.length > 0 ? audit.channels.join(', ') : 'none detected'],
  ];
  const keyWidth = Math.max(...rows.map(([key]) => key.length));
  const tableLines = rows.map(([key, val]) => `  ${dim(key.padEnd(keyWidth))}  ${k.bold(val)}`).join('\n');

  p.note(tableLines, `📊 Migration Audit — ${label} at ${source.path}`);
}

// ─── Migration flow ───────────────────────────────────────────────────────────

async function runMigrationFlow(): Promise<void> {
  const typeLabel: Record<string, string> = {
    openclaw: 'OpenClaw',
    nanoclaw: 'NanoClaw',
    cyndra: 'Cyndra',
  };

  // 1. Detect install
  const s = p.spinner();
  s.start('Scanning for existing installs…');
  const detected = await detectInstall();
  s.stop(
    detected
      ? k.green(`Found ${typeLabel[detected.type] ?? detected.type} at ${detected.path}`)
      : dim('No install auto-detected.'),
  );

  let source: MigrationSource;
  if (detected) {
    const use = ensure(
      await p.confirm({
        message: `Use ${typeLabel[detected.type] ?? detected.type} at ${detected.path}?`,
        initialValue: true,
      }),
    ) as boolean;
    source = use ? detected : await askManualPath();
  } else {
    source = await askManualPath();
  }

  // 2. Audit
  const s2 = p.spinner();
  s2.start('Auditing install…');
  const audit = await auditInstall(source);
  s2.stop('Audit complete.');
  printAuditReport(source, audit);

  // 3. What to migrate
  type SelectionOption = { value: MigrationSelection; label: string; hint: string };
  const selectionOptions: SelectionOption[] = [];
  if (audit.groups.length > 0) {
    selectionOptions.push({
      value: 'groups',
      label: 'Groups & memory',
      hint: `${audit.groups.length} group(s)`,
    });
  }
  if (audit.messageCount > 0) {
    selectionOptions.push({
      value: 'messages',
      label: 'Message history',
      hint: `${audit.messageCount.toLocaleString()} messages`,
    });
  }
  if (audit.skills.length > 0) {
    selectionOptions.push({
      value: 'skills',
      label: 'Custom skills',
      hint: `${audit.skills.length} file(s)`,
    });
  }
  if (audit.channels.length > 0 || audit.configFiles.includes('.env')) {
    selectionOptions.push({
      value: 'credentials',
      label: 'Channel credentials',
      hint: audit.channels.join(', ') || '.env',
    });
  }

  if (selectionOptions.length === 0) {
    p.log.warn('Nothing migratable was found in that directory.');
    p.outro(dim('Nothing to do.'));
    return;
  }

  const selections = ensure(
    await p.multiselect<MigrationSelection>({
      message: 'What would you like to migrate?',
      options: selectionOptions,
      required: true,
    }),
  ) as MigrationSelection[];

  // 4. Safety notice + confirm
  p.log.info(dim('This will NOT affect your existing installation. Your data there is untouched.'));
  const confirmed = ensure(await p.confirm({ message: 'Start migration?', initialValue: true })) as boolean;
  if (!confirmed) {
    p.cancel('Migration cancelled. Nothing was changed.');
    process.exit(0);
  }

  // 5. Run migration with progress
  const migSpinner = p.spinner();
  migSpinner.start('Migrating…');
  try {
    await runMigration(source, audit, selections, ({ step, detail }) => {
      migSpinner.message(detail ?? step);
    });
    migSpinner.stop(k.green('Migration complete.'));
  } catch (err) {
    migSpinner.stop(k.red('Migration failed.'));
    p.log.error(err instanceof Error ? err.message : String(err));
    const wantsRollback = ensure(
      await p.confirm({
        message: 'Roll back to pre-migration state?',
        initialValue: true,
      }),
    ) as boolean;
    if (wantsRollback) {
      const rb = p.spinner();
      rb.start('Rolling back…');
      try {
        await rollback(source);
        rb.stop(k.green('Rolled back successfully.'));
      } catch (rbErr) {
        rb.stop(k.red('Rollback also failed.'));
        p.log.error(rbErr instanceof Error ? rbErr.message : String(rbErr));
      }
    }
    process.exit(1);
  }

  // 6. Optionally deactivate source
  const label = typeLabel[source.type] ?? source.type;
  const wantsDeactivate = ensure(
    await p.confirm({
      message: `Would you like to deactivate ${label}? (Your data is safe — this adds a .disabled marker)`,
      initialValue: false,
    }),
  ) as boolean;
  if (wantsDeactivate) {
    deactivateSource(source);
    p.log.success(`${label} marked as deactivated.`);
  }

  p.outro(k.green('✅ Migration done!') + `  ClawBridge data is at ${k.bold(os.homedir() + '/.clawbridge')}`);
}

async function askManualPath(): Promise<MigrationSource> {
  while (true) {
    const input = ensure(
      await p.text({
        message: 'Enter the path to your existing install',
        placeholder: '~/openclaw',
        validate: validateRequired,
      }),
    ) as string;
    const result = resolveManualPath(input.trim().replace(/^~/, os.homedir()));
    if ('error' in result) {
      p.log.error(result.error);
      continue;
    }
    return result;
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  printBanner();
  p.intro(`${brandBold('Welcome to ClawBridge Agent setup.')}`);

  const mode = ensure(
    await p.select({
      message: 'How would you like to get started?',
      options: [
        { value: 'fresh', label: 'Fresh install' },
        { value: 'openclaw', label: 'Migrate from OpenClaw' },
        { value: 'nanoclaw', label: 'Migrate from NanoClaw / Cyndra' },
      ],
    }),
  ) as 'fresh' | 'openclaw' | 'nanoclaw';

  if (mode === 'fresh') {
    await runFreshInstall();
  } else {
    await runMigrationFlow();
  }
}

main().catch((err) => {
  p.log.error(err instanceof Error ? err.message : String(err));
  p.cancel('Setup aborted.');
  process.exit(1);
});
